### ISSUE TITLE
Linked on external website

### ISSUE THREAD

**Issue by ByElChe2020** [free-belarus/info#28]
FYI

Your website was linked at https://care-for-belarus.org/

Keep up the good work.

Thanx

**Comment by wasjawojasja** [comment]
@ByElChe2020 Hey, thank you! We decided to keep track of those sites, at this point it’s [in the wiki](https://github.com/free-belarus/info/wiki/%D0%9E-%D0%BD%D0%B0%D1%81-%D0%B2-%D0%A1%D0%9C%D0%98). I cannot find the link pointing to us on the website you provided at this moment, so I’m not updating that wiki entry with new information.

We keep the whole repository in Russian, because our target audience is in Belarus, majority of which speaks Russian. We do have plans to translate the whole thing to other languages, English included, later on. If you’re willing to contribute, you’re very welcome.

**Comment by wasjawojasja** [comment]
Anyway, doesn’t matter much to the initiative. Thank you for informing, keep up spreading the word about us. I’m closing the issue to keep the issues list cleaner.
